name: Build & Test

on: [push, pull_request]

jobs:

  test-docker-puppeteer-tryout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test docker-puppeteer-tryout
      run: |
        pwd
        cd docker-puppeteer-tryout
        docker-compose -f docker-compose.integration-tests.yml build tests
        docker-compose -f docker-compose.integration-tests.yml run tests
        ls screenshots/app.png
    - uses: actions/upload-artifact@v1
      with:
        name: test-screenshot.png
        path: docker-puppeteer-tryout/screenshots/app.png

  # This workflow contains a single job called "greet"
  greet:
    needs: test-docker-puppeteer-tryout
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
