name: Test

on: [push, pull_request]

jobs:

  test-docker-python-tryout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test docker-python-tryout
      run: |
        cd docker-python-tryout
          docker build .
        cd ..

  merge:
    runs-on: ubuntu-latest
    steps:
    - name: merge branch
      run: |
        ls -l