name: Test

on: [push, pull_request]

jobs:
  # This workflow contains a single job called "greet"
  merge:
    # needs: test-docker-puppeteer-tryout
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: merge branch
      run: |
        apt update
        apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        python3 -V
        python3 -m pip install pipenv
        PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
        PATH="$PATH:$PYTHON_BIN_PATH"

        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

        pipenv --help

        pipenv sync
        pipenv run python3 ./helloworld.py