name: Test

on: [push, pull_request]

jobs:
  # This workflow contains a single job called "greet"
  merge:
    # needs: test-docker-puppeteer-tryout
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: merge branch
      run: |
        ls -l
        pwd