name: Test

on: [push, pull_request]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: merge branch
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        python3 -m pip install pipenv

    - name: retry
      run: |
        which pipenv
